spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}/SIMPLAN?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USER}
    password: ${MYSQL_SECRET}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        dialect: org.hibernate.dialect.MySQL8InnoDBDialect
    generate-ddl: true
    open-in-view: false


  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_SECRET}

  jwt:
    secret: ${JWT_SECRET}